<script>
	import Header from "$lib/header/Header.svelte";
	import "../app.css";
</script>

<Header />

<main>
	<slot />
</main>

<footer>
	Powered by <a href="https://vercel.com/">Vercel</a>
	| Generated by
	<a href="https://github.com/OverflowCat/simpublish">Simpublish</a>
	| Made for <a href="https://simpread.pro/">SimpRead</a>
</footer>

<style>
	footer {
		text-align: center;
		height: 2rem;
	}
	main {
		padding: 1rem;
		width: 100%;
		max-width: 1024px;
		margin: 0 auto;
		box-sizing: border-box;
		height: calc(100% - 3rem);
	}
	/* 	main {
		flex: 1;
		display: flex;
		flex-direction: column;
		padding: 1rem;
		width: 100%;
		max-width: 1024px;
		margin: 0 auto;
		box-sizing: border-box;
	}
	@media (min-width: 480px) {
		footer {
			padding: 8px 0;
		}
	} */
</style>
