<script>
	import Header from "$lib/header/Header.svelte";
	import "../reset.css";
	import "../custom.css";
	import "carbon-components-svelte/css/all.css";
	import { Theme } from "carbon-components-svelte";
	let theme = "white"; // "white" | "g10" | "g80" | "g90" | "g100"
	import { onMount } from "svelte";
	onMount(() => {
		const mediaQueryListDark = window.matchMedia(
			"(prefers-color-scheme: dark)"
		);
		if (mediaQueryListDark.matches) theme = "g90";
		function handleChange(mediaQueryListEvent) {
			theme = mediaQueryListEvent.matches ? "g90" : "white";
		}
		mediaQueryListDark.addListener(handleChange);
	});
</script>

<Header />
<Theme bind:theme />

<main>
	<slot />
</main>

<footer>
	Powered by <a href="https://vercel.com/">Vercel</a>
	| Generated by
	<a href="https://github.com/OverflowCat/simpublish">Simpublish</a>
	| Made for <a href="https://simpread.pro/">SimpRead</a>
</footer>

<style>
	footer {
		text-align: center;
		height: 2rem;
	}
	main {
		padding: 1rem;
		width: 100%;
		max-width: 1024px;
		margin: 0 auto;
		box-sizing: border-box;
		height: calc(100% - 3rem);
	}
	/* 	main {
		flex: 1;
		display: flex;
		flex-direction: column;
		padding: 1rem;
		width: 100%;
		max-width: 1024px;
		margin: 0 auto;
		box-sizing: border-box;
	}
	@media (min-width: 480px) {
		footer {
			padding: 8px 0;
		}
	} */
</style>
